@startuml UseCaseDiagram
' Definindo atores
actor Actor

' Caso de uso principal
usecase (UC01) as "UC01"

' Relações entre atores e caso de uso
Actor -> (UC01)

' Dependências de outros casos de uso

@enduml